server:
  port: 80
      
#mybatis pageHelper
pagehelper: 
  helper-dialect: mysql
  reasonable: true
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  #Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/final?characterEncoding=UTF-8&serverTimezone=UTC&SSL=false
    username: root
    password: wl112454
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet: 
    ## MULTIPART (MultipartProperties)
    # Enable multipart uploads
    multipart:
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB
      
# circular reference
  main:
    allow-circular-references: true

# google login signup
  security: 
    oauth2: 
      client: 
        registration: 
          google: 
            client-id: 302550495128-bp0lmfb06k19t14r2jl34i80aourekqq.apps.googleusercontent.com
            client-secret: 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
            scope: 
            - profile
            - email

# facebook login signup
          facebook: 
            client-id: 2928634937429074
            client-secret: 8540b6c3091355e41f45c0ba9552aa2c
            scope: 
            - public_profile
            - email

# naver login signup
          naver: 
            client-id: bTQGMQDRxIv70I665l6X
            client-secret: dKzaGSZmr7
            scope: 
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:80/login/oauth2/code/naver
            
# kakao login signup
          kakao: 
            client-id: bdc8fbc69087fc57ee4309f130d457bc
            client-secret: COTrUxUGRVvutbqWLQ7x3jCUn4XYGoFg
            scope: 
            - profile_nickname
            - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:80/login/oauth2/code/kakao
            client-authentication-method: POST
            
        # 네이버, 카카오는 provider가 따로 없기 때문에 설정해준다.
        provider: 
          naver: 
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            # 회원정보를 json으로 받는데, response라는 키값으로 네이버가 리턴해준다.
            user-name-attribute: response
            
          kakao: 
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account
            # 회원정보를 json으로 받는데, kakao_account라는 키값으로 카카오가 리턴해준다.
            
             


